INFO 2024-08-07 21:28:42,340 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:37:50,591 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-07 22:37:52,410 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:37:59,367 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-07 22:38:00,956 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:38:16,424 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-07 22:38:18,399 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:38:58,386 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\gateway\views.py changed, reloading.
INFO 2024-08-07 22:38:59,613 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:39:25,790 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\gateway\views.py changed, reloading.
INFO 2024-08-07 22:39:27,182 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-07 22:39:42,924 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-07 22:39:42,925 views views.py:35 Started login in gateWay view
INFO 2024-08-07 22:39:44,293 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-07 22:39:44,296 middleware middleware.py:20 Response: 200 OK (1.37s)
INFO 2024-08-07 22:39:44,296 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-07 22:40:00,071 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
ERROR 2024-08-07 22:40:21,336 views views.py:107 gateway_view RequestException for service: service1, endpoint: generate-model-paper, error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8001/qizGenerator/generate-model-paper/
INFO 2024-08-07 22:40:21,338 middleware middleware.py:20 Response: 500 Internal Server Error (21.27s)
ERROR 2024-08-07 22:40:21,339 log log.py:241 Internal Server Error: /api/service1/generate-model-paper/
ERROR 2024-08-07 22:40:21,339 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 500 118
INFO 2024-08-07 22:41:11,892 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
INFO 2024-08-07 22:41:42,122 views views.py:103 gateway_view success for service: service1, endpoint: generate-model-paper
INFO 2024-08-07 22:41:42,122 middleware middleware.py:20 Response: 200 OK (30.23s)
INFO 2024-08-07 22:41:42,134 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 200 5881
INFO 2024-08-08 14:01:05,778 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-08 14:01:09,002 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-08 14:01:17,359 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-08 14:01:19,786 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-08 14:01:30,146 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-08 14:01:32,389 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-08 14:01:50,069 basehttp basehttp.py:212 code 400, message Bad request version ('À\x13À')
ERROR 2024-08-08 14:01:50,070 basehttp basehttp.py:192 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2024-08-08 14:02:00,927 basehttp basehttp.py:212 code 400, message Bad request syntax ('\x16\x03\x01\x00å\x01\x00\x00á\x03\x03$áo»Y')
ERROR 2024-08-08 14:02:00,928 basehttp basehttp.py:192 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2024-08-08 14:03:24,719 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-08 14:03:26,637 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 20:35:32,996 basehttp basehttp.py:212 code 400, message Bad request version ('À\x13À')
ERROR 2024-08-11 20:35:33,007 basehttp basehttp.py:192 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2024-08-11 20:36:59,802 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 20:36:59,815 views views.py:35 Started login in gateWay view
INFO 2024-08-11 20:37:01,349 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-11 20:37:01,356 middleware middleware.py:20 Response: 200 OK (1.55s)
INFO 2024-08-11 20:37:01,356 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-11 20:37:22,968 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
ERROR 2024-08-11 20:37:44,365 views views.py:107 gateway_view RequestException for service: service1, endpoint: generate-model-paper, error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8001/qizGenerator/generate-model-paper/
INFO 2024-08-11 20:37:44,366 middleware middleware.py:20 Response: 500 Internal Server Error (21.40s)
ERROR 2024-08-11 20:37:44,367 log log.py:241 Internal Server Error: /api/service1/generate-model-paper/
ERROR 2024-08-11 20:37:44,368 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 500 118
INFO 2024-08-11 20:42:25,655 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
INFO 2024-08-11 20:42:25,656 middleware middleware.py:20 Response: 403 Forbidden (0.00s)
WARNING 2024-08-11 20:42:25,656 log log.py:241 Forbidden: /api/service1/generate-model-paper/
WARNING 2024-08-11 20:42:25,656 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 403 37
INFO 2024-08-11 20:42:32,586 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 20:42:32,586 views views.py:35 Started login in gateWay view
INFO 2024-08-11 20:42:33,297 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-11 20:42:33,297 middleware middleware.py:20 Response: 200 OK (0.71s)
INFO 2024-08-11 20:42:33,297 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-11 20:42:43,519 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
ERROR 2024-08-11 20:43:04,796 views views.py:107 gateway_view RequestException for service: service1, endpoint: generate-model-paper, error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8001/qizGenerator/generate-model-paper/
INFO 2024-08-11 20:43:04,797 middleware middleware.py:20 Response: 500 Internal Server Error (21.28s)
ERROR 2024-08-11 20:43:04,797 log log.py:241 Internal Server Error: /api/service1/generate-model-paper/
ERROR 2024-08-11 20:43:04,798 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 500 118
INFO 2024-08-11 20:43:15,943 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-11 20:43:17,879 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 20:43:21,748 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-11 20:43:23,224 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 20:43:50,565 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
INFO 2024-08-11 20:44:17,856 views views.py:103 gateway_view success for service: service1, endpoint: generate-model-paper
INFO 2024-08-11 20:44:17,856 middleware middleware.py:20 Response: 200 OK (27.29s)
INFO 2024-08-11 20:44:17,868 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 200 5644
INFO 2024-08-11 20:45:39,316 middleware middleware.py:13 Request: GET /api/service1/generate-model-paper/
INFO 2024-08-11 20:46:05,810 views views.py:103 gateway_view success for service: service1, endpoint: generate-model-paper
INFO 2024-08-11 20:46:05,813 middleware middleware.py:20 Response: 200 OK (26.50s)
INFO 2024-08-11 20:46:05,814 basehttp basehttp.py:212 "GET /api/service1/generate-model-paper/ HTTP/1.1" 200 5820
INFO 2024-08-11 21:28:49,465 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-11 21:28:49,468 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:28:49,469 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 164
INFO 2024-08-11 21:28:51,797 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-11 21:28:51,799 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:28:51,800 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 164
INFO 2024-08-11 21:28:52,583 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-11 21:28:52,586 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:28:52,588 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 164
INFO 2024-08-11 21:29:03,513 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-11 21:29:03,516 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:29:03,517 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 164
INFO 2024-08-11 21:36:05,352 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-11 21:36:06,839 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 21:36:33,015 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-11 21:36:34,529 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 21:37:13,256 autoreload autoreload.py:266 J:\research project new\researchProject\apiGateway\api_gateway\settings.py changed, reloading.
INFO 2024-08-11 21:37:14,807 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-11 21:49:52,152 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-11 21:49:52,154 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:49:52,155 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-08-11 21:49:52,157 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 21:49:52,158 views views.py:35 Started login in gateWay view
INFO 2024-08-11 21:49:53,540 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-11 21:49:53,541 middleware middleware.py:20 Response: 200 OK (1.38s)
INFO 2024-08-11 21:49:53,542 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-11 21:51:37,368 middleware middleware.py:13 Request: OPTIONS /api/register/
INFO 2024-08-11 21:51:37,369 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-11 21:51:37,370 basehttp basehttp.py:212 "OPTIONS /api/register/ HTTP/1.1" 200 0
INFO 2024-08-11 21:51:37,371 middleware middleware.py:13 Request: POST /api/register/
INFO 2024-08-11 21:51:37,372 views views.py:20 Started register in gateWay view
INFO 2024-08-11 21:51:38,193 views views.py:25 End register in gateWay view: Successful
INFO 2024-08-11 21:51:38,196 middleware middleware.py:20 Response: 201 Created (0.82s)
INFO 2024-08-11 21:51:38,200 basehttp basehttp.py:212 "POST /api/register/ HTTP/1.1" 201 68
INFO 2024-08-11 21:51:57,929 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 21:51:57,931 views views.py:35 Started login in gateWay view
INFO 2024-08-11 21:51:58,563 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-11 21:51:58,563 middleware middleware.py:20 Response: 200 OK (0.63s)
INFO 2024-08-11 21:51:58,563 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-11 21:52:20,824 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 21:52:20,825 views views.py:35 Started login in gateWay view
ERROR 2024-08-11 21:52:20,892 views views.py:52 End login in gateWay view: Fail: Exception UserEdu matching query does not exist.
INFO 2024-08-11 21:52:20,893 middleware middleware.py:20 Response: 401 Unauthorized (0.07s)
WARNING 2024-08-11 21:52:20,893 log log.py:241 Unauthorized: /api/login/
WARNING 2024-08-11 21:52:20,893 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 401 32
INFO 2024-08-11 21:55:04,367 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-11 21:55:04,369 views views.py:35 Started login in gateWay view
INFO 2024-08-11 21:55:04,927 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-11 21:55:04,928 middleware middleware.py:20 Response: 200 OK (0.56s)
INFO 2024-08-11 21:55:04,929 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-12 16:06:42,685 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-12 16:06:42,698 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-12 16:06:42,707 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-08-12 16:06:42,710 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 16:06:42,719 views views.py:35 Started login in gateWay view
INFO 2024-08-12 16:06:45,518 views views.py:49 End login in gateWay view: Fail: Invalid credentials
INFO 2024-08-12 16:06:45,522 middleware middleware.py:20 Response: 401 Unauthorized (2.81s)
WARNING 2024-08-12 16:06:45,523 log log.py:241 Unauthorized: /api/login/
WARNING 2024-08-12 16:06:45,525 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 401 32
INFO 2024-08-12 16:06:49,537 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 16:06:49,539 views views.py:35 Started login in gateWay view
INFO 2024-08-12 16:06:50,969 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-12 16:06:50,969 middleware middleware.py:20 Response: 200 OK (1.43s)
INFO 2024-08-12 16:06:50,969 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-12 16:36:45,848 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 16:36:45,850 views views.py:35 Started login in gateWay view
INFO 2024-08-12 16:36:48,138 views views.py:49 End login in gateWay view: Fail: Invalid credentials
INFO 2024-08-12 16:36:48,139 middleware middleware.py:20 Response: 401 Unauthorized (2.29s)
WARNING 2024-08-12 16:36:48,139 log log.py:241 Unauthorized: /api/login/
WARNING 2024-08-12 16:36:48,139 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 401 32
INFO 2024-08-12 16:36:55,853 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 16:36:55,855 views views.py:35 Started login in gateWay view
INFO 2024-08-12 16:36:57,182 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-12 16:36:57,185 middleware middleware.py:20 Response: 200 OK (1.33s)
INFO 2024-08-12 16:36:57,187 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-12 16:47:53,905 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 16:47:53,907 views views.py:35 Started login in gateWay view
INFO 2024-08-12 16:47:55,727 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-12 16:47:55,728 middleware middleware.py:20 Response: 200 OK (1.82s)
INFO 2024-08-12 16:47:55,729 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-12 21:56:45,427 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-12 22:04:30,869 middleware middleware.py:13 Request: OPTIONS /api/register/
INFO 2024-08-12 22:04:30,869 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-12 22:04:30,870 basehttp basehttp.py:212 "OPTIONS /api/register/ HTTP/1.1" 200 0
INFO 2024-08-12 22:04:30,880 middleware middleware.py:13 Request: POST /api/register/
INFO 2024-08-12 22:04:30,881 views views.py:20 Started register in gateWay view
INFO 2024-08-12 22:04:31,606 views views.py:25 End register in gateWay view: Successful
INFO 2024-08-12 22:04:31,608 middleware middleware.py:20 Response: 201 Created (0.73s)
INFO 2024-08-12 22:04:31,608 basehttp basehttp.py:212 "POST /api/register/ HTTP/1.1" 201 93
INFO 2024-08-12 22:04:46,172 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-08-12 22:04:46,173 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-08-12 22:04:46,175 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-08-12 22:04:46,183 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-08-12 22:04:46,184 views views.py:35 Started login in gateWay view
INFO 2024-08-12 22:04:46,544 views views.py:43 End login in gateWay view: Successful
INFO 2024-08-12 22:04:46,544 middleware middleware.py:20 Response: 200 OK (0.36s)
INFO 2024-08-12 22:04:46,545 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-08-15 23:57:22,571 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-16 00:02:20,858 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-16 12:31:21,137 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-20 13:14:48,250 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-20 13:56:57,399 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-08-20 15:01:03,681 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-07 20:09:54,299 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 13:39:57,202 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 14:57:11,551 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 15:46:57,065 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 19:20:52,049 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 19:46:00,007 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 19:47:19,335 middleware middleware.py:13 Request: OPTIONS /api/register/
INFO 2024-09-09 19:47:19,336 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-09 19:47:19,338 basehttp basehttp.py:212 "OPTIONS /api/register/ HTTP/1.1" 200 0
INFO 2024-09-09 19:47:19,345 middleware middleware.py:13 Request: POST /api/register/
INFO 2024-09-09 19:47:19,345 views views.py:20 Started register in gateWay view
INFO 2024-09-09 19:47:20,807 views views.py:25 End register in gateWay view: Successful
INFO 2024-09-09 19:47:20,807 middleware middleware.py:20 Response: 201 Created (1.46s)
INFO 2024-09-09 19:47:20,807 basehttp basehttp.py:212 "POST /api/register/ HTTP/1.1" 201 79
INFO 2024-09-09 19:48:15,626 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-09-09 19:48:15,627 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-09 19:48:15,628 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-09-09 19:48:15,639 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 19:48:15,641 views views.py:35 Started login in gateWay view
INFO 2024-09-09 19:48:16,074 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 19:48:16,074 middleware middleware.py:20 Response: 200 OK (0.43s)
INFO 2024-09-09 19:48:16,074 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-09 21:50:05,339 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-09-09 21:50:05,342 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-09 21:50:05,343 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-09-09 21:50:05,349 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 21:50:05,353 views views.py:35 Started login in gateWay view
INFO 2024-09-09 21:50:06,195 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 21:50:06,196 middleware middleware.py:20 Response: 200 OK (0.85s)
INFO 2024-09-09 21:50:06,198 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-09 21:56:04,582 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 21:56:04,584 views views.py:35 Started login in gateWay view
INFO 2024-09-09 21:56:05,040 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 21:56:05,042 middleware middleware.py:20 Response: 200 OK (0.46s)
INFO 2024-09-09 21:56:05,043 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-09 22:00:05,960 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 22:00:05,961 views views.py:35 Started login in gateWay view
INFO 2024-09-09 22:00:06,379 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 22:00:06,381 middleware middleware.py:20 Response: 200 OK (0.42s)
INFO 2024-09-09 22:00:06,382 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-09 22:10:53,831 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-09 22:11:14,952 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 22:11:14,953 views views.py:35 Started login in gateWay view
INFO 2024-09-09 22:11:16,027 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 22:11:16,028 middleware middleware.py:20 Response: 200 OK (1.08s)
INFO 2024-09-09 22:11:16,029 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-09 23:04:50,191 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-09 23:04:50,193 views views.py:35 Started login in gateWay view
INFO 2024-09-09 23:04:50,646 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-09 23:04:50,647 middleware middleware.py:20 Response: 200 OK (0.46s)
INFO 2024-09-09 23:04:50,649 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-10 08:53:00,173 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-10 08:54:13,250 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-09-10 08:54:13,250 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-10 08:54:13,250 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-09-10 08:54:13,258 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:54:13,258 views views.py:35 Started login in gateWay view
INFO 2024-09-10 08:54:20,238 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:54:20,238 views views.py:35 Started login in gateWay view
INFO 2024-09-10 08:54:24,378 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:54:24,378 views views.py:35 Started login in gateWay view
INFO 2024-09-10 08:54:26,687 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:54:26,687 views views.py:35 Started login in gateWay view
ERROR 2024-09-10 08:54:33,513 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1695, in connect
    sock = _configured_socket(self.address, self.opts)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1313, in _configured_socket
    sock = _create_connection(address, options)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1297, in _create_connection
    raise err
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1290, in _create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\document.py", line 232, in _get_collection
    cls.ensure_indexes()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\document.py", line 916, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\collection.py", line 2120, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\collection.py", line 1973, in __create_indexes
    with self._conn_for_writes(session, operation=_Op.CREATE_INDEXES) as conn:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1266, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1767, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1926, in _get_conn
    conn = self.connect(handler=handler)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1715, in connect
    _raise_connection_failure(self.address, error, timeout_details=details)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 419, in _raise_connection_failure
    raise NetworkTimeout(msg) from error
pymongo.errors.NetworkTimeout: ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: timed out (configured timeouts: connectTimeoutMS: 20000.0ms)
INFO 2024-09-10 08:54:33,529 middleware middleware.py:20 Response: 500 Internal Server Error (20.27s)
ERROR 2024-09-10 08:54:33,529 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 185757
INFO 2024-09-10 08:54:46,667 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:54:46,667 views views.py:35 Started login in gateWay view
INFO 2024-09-10 08:55:07,141 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:55:07,141 views views.py:35 Started login in gateWay view
INFO 2024-09-10 08:55:21,135 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:55:21,136 views views.py:35 Started login in gateWay view
ERROR 2024-09-10 08:55:24,793 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:55:24,793 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:55:24,824 middleware middleware.py:20 Response: 500 Internal Server Error (60.45s)
INFO 2024-09-10 08:55:24,824 views views.py:35 Started login in gateWay view
ERROR 2024-09-10 08:55:24,831 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 200241
INFO 2024-09-10 08:55:25,529 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:55:25,533 views views.py:35 Started login in gateWay view
ERROR 2024-09-10 08:55:27,342 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:55:27,369 middleware middleware.py:20 Response: 500 Internal Server Error (60.68s)
ERROR 2024-09-10 08:55:27,369 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 200240
INFO 2024-09-10 08:55:28,059 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 08:55:28,059 views views.py:35 Started login in gateWay view
ERROR 2024-09-10 08:55:30,388 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1695, in connect
    sock = _configured_socket(self.address, self.opts)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1313, in _configured_socket
    sock = _create_connection(address, options)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1266, in _create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2358, in run
    self._check_last_error()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2432, in _check_last_error
    raise self._last_error
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2485, in _read
    with self._client._conn_from_server(self._read_pref, self._server, self._session) as (
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1357, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1266, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1767, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1926, in _get_conn
    conn = self.connect(handler=handler)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 1715, in connect
    _raise_connection_failure(self.address, error, timeout_details=details)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\pool.py", line 427, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: connectTimeoutMS: 20000.0ms)
INFO 2024-09-10 08:55:30,413 middleware middleware.py:20 Response: 500 Internal Server Error (70.18s)
ERROR 2024-09-10 08:55:30,414 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 225114
ERROR 2024-09-10 08:55:47,468 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:55:47,482 middleware middleware.py:20 Response: 500 Internal Server Error (60.82s)
ERROR 2024-09-10 08:55:47,482 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 200241
ERROR 2024-09-10 08:56:07,696 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:56:07,706 middleware middleware.py:20 Response: 500 Internal Server Error (60.57s)
ERROR 2024-09-10 08:56:07,708 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 200241
ERROR 2024-09-10 08:56:15,365 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:56:15,377 middleware middleware.py:20 Response: 500 Internal Server Error (54.24s)
ERROR 2024-09-10 08:56:15,377 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 196236
ERROR 2024-09-10 08:56:15,448 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:56:15,462 middleware middleware.py:20 Response: 500 Internal Server Error (49.93s)
ERROR 2024-09-10 08:56:15,463 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 196235
ERROR 2024-09-10 08:56:15,913 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
ERROR 2024-09-10 08:56:15,944 log log.py:241 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\gateway\views.py", line 39, in login
    user = UserEdu.objects.get(email=serializer.validated_data['email'])
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 274, in get
    result = next(queryset)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\mongoengine\queryset\base.py", line 1629, in __next__
    raw_doc = next(self._cursor)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\ASUS\Documents\GitHub\researchProject\apiGateway\Venv\lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66dfbb93a7f906c7e9781a2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-00.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-01.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-lbxu2ew-shard-00-02.8grcvgo.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
INFO 2024-09-10 08:56:15,944 middleware middleware.py:20 Response: 500 Internal Server Error (47.88s)
INFO 2024-09-10 08:56:15,951 middleware middleware.py:20 Response: 500 Internal Server Error (51.13s)
ERROR 2024-09-10 08:56:15,951 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 196235
ERROR 2024-09-10 08:56:15,954 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 500 196235
INFO 2024-09-10 09:30:33,441 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-10 09:31:43,249 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 09:31:43,249 views views.py:35 Started login in gateWay view
INFO 2024-09-10 09:31:44,309 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-10 09:31:44,309 middleware middleware.py:20 Response: 200 OK (1.06s)
INFO 2024-09-10 09:31:44,309 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-10 09:37:33,555 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-10 09:38:58,604 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 09:38:58,604 views views.py:35 Started login in gateWay view
INFO 2024-09-10 09:38:59,688 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-10 09:38:59,704 middleware middleware.py:20 Response: 200 OK (1.10s)
INFO 2024-09-10 09:38:59,704 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-10 09:46:20,134 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 09:46:20,134 views views.py:35 Started login in gateWay view
INFO 2024-09-10 09:46:20,514 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-10 09:46:20,514 middleware middleware.py:20 Response: 200 OK (0.38s)
INFO 2024-09-10 09:46:20,514 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-10 09:49:32,752 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-10 09:49:32,752 views views.py:35 Started login in gateWay view
INFO 2024-09-10 09:49:33,068 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-10 09:49:33,068 middleware middleware.py:20 Response: 200 OK (0.32s)
INFO 2024-09-10 09:49:33,068 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-12 23:30:03,559 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-09-12 23:30:48,023 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-09-12 23:30:48,024 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-12 23:30:48,025 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-09-12 23:30:48,028 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-12 23:30:48,028 views views.py:35 Started login in gateWay view
INFO 2024-09-12 23:30:48,974 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-12 23:30:48,974 middleware middleware.py:20 Response: 200 OK (0.95s)
INFO 2024-09-12 23:30:48,974 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-09-12 23:34:26,100 middleware middleware.py:13 Request: OPTIONS /api/register/
INFO 2024-09-12 23:34:26,101 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-09-12 23:34:26,102 basehttp basehttp.py:212 "OPTIONS /api/register/ HTTP/1.1" 200 0
INFO 2024-09-12 23:34:26,110 middleware middleware.py:13 Request: POST /api/register/
INFO 2024-09-12 23:34:26,111 views views.py:20 Started register in gateWay view
INFO 2024-09-12 23:34:26,582 views views.py:25 End register in gateWay view: Successful
INFO 2024-09-12 23:34:26,582 middleware middleware.py:20 Response: 201 Created (0.47s)
INFO 2024-09-12 23:34:26,582 basehttp basehttp.py:212 "POST /api/register/ HTTP/1.1" 201 69
INFO 2024-09-12 23:34:43,723 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-09-12 23:34:43,725 views views.py:35 Started login in gateWay view
INFO 2024-09-12 23:34:44,101 views views.py:43 End login in gateWay view: Successful
INFO 2024-09-12 23:34:44,116 middleware middleware.py:20 Response: 200 OK (0.39s)
INFO 2024-09-12 23:34:44,116 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-21 21:01:46,383 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-21 21:03:38,455 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-10-21 21:03:38,456 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-10-21 21:03:38,457 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-10-21 21:03:38,459 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-21 21:03:38,460 views views.py:35 Started login in gateWay view
INFO 2024-10-21 21:03:39,066 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-21 21:03:39,066 middleware middleware.py:20 Response: 200 OK (0.61s)
INFO 2024-10-21 21:03:39,066 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-21 21:07:43,558 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-21 21:07:43,559 views views.py:35 Started login in gateWay view
INFO 2024-10-21 21:07:43,786 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-21 21:07:43,787 middleware middleware.py:20 Response: 200 OK (0.23s)
INFO 2024-10-21 21:07:43,788 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-21 22:02:07,323 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-21 22:03:05,699 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-21 22:03:05,699 views views.py:35 Started login in gateWay view
INFO 2024-10-21 22:03:06,310 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-21 22:03:06,311 middleware middleware.py:20 Response: 200 OK (0.61s)
INFO 2024-10-21 22:03:06,312 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-22 11:35:16,670 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-22 11:36:21,510 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-10-22 11:36:21,511 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-10-22 11:36:21,512 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-10-22 11:36:21,514 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-22 11:36:21,516 views views.py:35 Started login in gateWay view
INFO 2024-10-22 11:36:22,124 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-22 11:36:22,124 middleware middleware.py:20 Response: 200 OK (0.61s)
INFO 2024-10-22 11:36:22,124 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-22 11:57:15,400 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-22 11:58:57,971 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-22 11:58:57,974 views views.py:35 Started login in gateWay view
INFO 2024-10-22 11:58:58,689 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-22 11:58:58,689 middleware middleware.py:20 Response: 200 OK (0.72s)
INFO 2024-10-22 11:58:58,689 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-22 12:14:53,999 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-22 12:15:35,502 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-22 12:15:35,505 views views.py:35 Started login in gateWay view
INFO 2024-10-22 12:15:36,210 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-22 12:15:36,211 middleware middleware.py:20 Response: 200 OK (0.71s)
INFO 2024-10-22 12:15:36,213 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-22 17:37:17,964 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-22 17:39:10,642 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-10-22 17:39:10,644 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-10-22 17:39:10,644 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-10-22 17:39:10,646 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-22 17:39:10,647 views views.py:35 Started login in gateWay view
INFO 2024-10-22 17:39:11,473 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-22 17:39:11,474 middleware middleware.py:20 Response: 200 OK (0.83s)
INFO 2024-10-22 17:39:11,475 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-22 17:57:58,618 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-22 17:57:58,619 views views.py:35 Started login in gateWay view
INFO 2024-10-22 17:57:58,982 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-22 17:57:58,982 middleware middleware.py:20 Response: 200 OK (0.36s)
INFO 2024-10-22 17:57:58,982 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
INFO 2024-10-23 20:43:16,788 autoreload autoreload.py:668 Watching for file changes with StatReloader
INFO 2024-10-23 20:44:05,680 middleware middleware.py:13 Request: OPTIONS /api/login/
INFO 2024-10-23 20:44:05,682 middleware middleware.py:20 Response: 200 OK (0.00s)
INFO 2024-10-23 20:44:05,684 basehttp basehttp.py:212 "OPTIONS /api/login/ HTTP/1.1" 200 0
INFO 2024-10-23 20:44:05,688 middleware middleware.py:13 Request: POST /api/login/
INFO 2024-10-23 20:44:05,692 views views.py:35 Started login in gateWay view
INFO 2024-10-23 20:44:06,398 views views.py:43 End login in gateWay view: Successful
INFO 2024-10-23 20:44:06,398 middleware middleware.py:20 Response: 200 OK (0.71s)
INFO 2024-10-23 20:44:06,398 basehttp basehttp.py:212 "POST /api/login/ HTTP/1.1" 200 380
